CREAT T_PS__PACIENTE (
    id_paciente number generated by default as identity,
    nome varchar2(255) ,
    telefone varchar2(20) ,
    nascimento date ,
    convenio varchar2(255) ,
    primary key (id_paciente)
);